#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : slirp4netns
Version  : 1.3.1
Release  : 5
URL      : https://github.com/rootless-containers/slirp4netns/archive/v1.3.1/slirp4netns-1.3.1.tar.gz
Source0  : https://github.com/rootless-containers/slirp4netns/archive/v1.3.1/slirp4netns-1.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: slirp4netns-bin = %{version}-%{release}
Requires: slirp4netns-license = %{version}-%{release}
Requires: slirp4netns-man = %{version}-%{release}
BuildRequires : iproute2
BuildRequires : iputils
BuildRequires : jq
BuildRequires : nmap-extras
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libseccomp)
BuildRequires : pkgconfig(slirp)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-add-absolute-path-of-binary.patch
Patch2: 0002-disable-failing-test-for-future-debug.patch

%description
# slirp4netns: User-mode networking for unprivileged network namespaces
slirp4netns provides user-mode networking ("slirp") for unprivileged network namespaces.

%package bin
Summary: bin components for the slirp4netns package.
Group: Binaries
Requires: slirp4netns-license = %{version}-%{release}

%description bin
bin components for the slirp4netns package.


%package license
Summary: license components for the slirp4netns package.
Group: Default

%description license
license components for the slirp4netns package.


%package man
Summary: man components for the slirp4netns package.
Group: Default

%description man
man components for the slirp4netns package.


%prep
%setup -q -n slirp4netns-1.3.1
cd %{_builddir}/slirp4netns-1.3.1
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a slirp4netns-1.3.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720032828
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720032828
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/slirp4netns
cp %{_builddir}/slirp4netns-%{version}/COPYING %{buildroot}/usr/share/package-licenses/slirp4netns/9e17993c507c79f83f3e32e544be51d33daa58fb || :
cp %{_builddir}/slirp4netns-%{version}/vendor/parson/LICENSE %{buildroot}/usr/share/package-licenses/slirp4netns/1518f228adf46f7d96f40a5d08059d24360ed9f2 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/slirp4netns
/usr/bin/slirp4netns

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/slirp4netns/1518f228adf46f7d96f40a5d08059d24360ed9f2
/usr/share/package-licenses/slirp4netns/9e17993c507c79f83f3e32e544be51d33daa58fb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/slirp4netns.1
