#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : slirp4netns
Version  : 1.2.0
Release  : 3
URL      : https://github.com/rootless-containers/slirp4netns/archive/v1.2.0/slirp4netns-1.2.0.tar.gz
Source0  : https://github.com/rootless-containers/slirp4netns/archive/v1.2.0/slirp4netns-1.2.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: slirp4netns-bin = %{version}-%{release}
Requires: slirp4netns-license = %{version}-%{release}
Requires: slirp4netns-man = %{version}-%{release}
BuildRequires : iproute2
BuildRequires : iputils
BuildRequires : jq
BuildRequires : nmap-extras
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libseccomp)
BuildRequires : pkgconfig(slirp)
Patch1: 0001-add-absolute-path-of-binary.patch
Patch2: 0002-disable-failing-test-for-future-debug.patch

%description
# slirp4netns: User-mode networking for unprivileged network namespaces
slirp4netns provides user-mode networking ("slirp") for unprivileged network namespaces.

%package bin
Summary: bin components for the slirp4netns package.
Group: Binaries
Requires: slirp4netns-license = %{version}-%{release}

%description bin
bin components for the slirp4netns package.


%package license
Summary: license components for the slirp4netns package.
Group: Default

%description license
license components for the slirp4netns package.


%package man
Summary: man components for the slirp4netns package.
Group: Default

%description man
man components for the slirp4netns package.


%prep
%setup -q -n slirp4netns-1.2.0
cd %{_builddir}/slirp4netns-1.2.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672201438
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1672201438
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/slirp4netns
cp %{_builddir}/slirp4netns-%{version}/COPYING %{buildroot}/usr/share/package-licenses/slirp4netns/9e17993c507c79f83f3e32e544be51d33daa58fb
cp %{_builddir}/slirp4netns-%{version}/vendor/parson/LICENSE %{buildroot}/usr/share/package-licenses/slirp4netns/86650c9716da66779ed3b0f31966006389e88329
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/slirp4netns

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/slirp4netns/86650c9716da66779ed3b0f31966006389e88329
/usr/share/package-licenses/slirp4netns/9e17993c507c79f83f3e32e544be51d33daa58fb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/slirp4netns.1
