#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
#
Name     : slirp4netns
Version  : 1.2.1
Release  : 4
URL      : https://github.com/rootless-containers/slirp4netns/archive/v1.2.1/slirp4netns-1.2.1.tar.gz
Source0  : https://github.com/rootless-containers/slirp4netns/archive/v1.2.1/slirp4netns-1.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: slirp4netns-bin = %{version}-%{release}
Requires: slirp4netns-license = %{version}-%{release}
Requires: slirp4netns-man = %{version}-%{release}
BuildRequires : iproute2
BuildRequires : iputils
BuildRequires : jq
BuildRequires : nmap-extras
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libseccomp)
BuildRequires : pkgconfig(slirp)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-add-absolute-path-of-binary.patch
Patch2: 0002-disable-failing-test-for-future-debug.patch

%description
# slirp4netns: User-mode networking for unprivileged network namespaces
slirp4netns provides user-mode networking ("slirp") for unprivileged network namespaces.

%package bin
Summary: bin components for the slirp4netns package.
Group: Binaries
Requires: slirp4netns-license = %{version}-%{release}

%description bin
bin components for the slirp4netns package.


%package license
Summary: license components for the slirp4netns package.
Group: Default

%description license
license components for the slirp4netns package.


%package man
Summary: man components for the slirp4netns package.
Group: Default

%description man
man components for the slirp4netns package.


%prep
%setup -q -n slirp4netns-1.2.1
cd %{_builddir}/slirp4netns-1.2.1
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a slirp4netns-1.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692643240
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1692643240
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/slirp4netns
cp %{_builddir}/slirp4netns-%{version}/COPYING %{buildroot}/usr/share/package-licenses/slirp4netns/9e17993c507c79f83f3e32e544be51d33daa58fb || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/slirp4netns
/usr/bin/slirp4netns

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/slirp4netns/9e17993c507c79f83f3e32e544be51d33daa58fb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/slirp4netns.1
